namespace Wpf_For_Test_File_Generator_And_Sorter.Helpers;

public static class WordLibrary
{
    private static readonly byte[][] Words =
    [
        "apple"u8.ToArray(),
        "banana"u8.ToArray(),
        "cherry"u8.ToArray(),
        "date"u8.ToArray(),
        "elderberry"u8.ToArray(),
        "fig"u8.ToArray(),
        "grape"u8.ToArray(),
        "honeydew"u8.ToArray(),
        "kiwi"u8.ToArray(),
        "lemon"u8.ToArray(),
        "mango"u8.ToArray(),
        "orange"u8.ToArray(),
        "peach"u8.ToArray(),
        "pineapple"u8.ToArray(),
        "strawberry"u8.ToArray(),
        "watermelon"u8.ToArray(),
        "blueberry"u8.ToArray(),
        "avocado"u8.ToArray(),
        "coconut"u8.ToArray(),
        "pear"u8.ToArray(),
        "apricot"u8.ToArray(),
        "plum"u8.ToArray(),
        "raspberry"u8.ToArray(),

        "time"u8.ToArray(),
        "day"u8.ToArray(),
        "year"u8.ToArray(),
        "world"u8.ToArray(),
        "life"u8.ToArray(),
        "house"u8.ToArray(),
        "place"u8.ToArray(),
        "work"u8.ToArray(),
        "water"u8.ToArray(),
        "people"u8.ToArray(),
        "family"u8.ToArray(),
        "friend"u8.ToArray(),
        "city"u8.ToArray(),
        "night"u8.ToArray(),
        "morning"u8.ToArray(),
        "sun"u8.ToArray(),
        "moon"u8.ToArray(),
        "star"u8.ToArray(),
        "tree"u8.ToArray(),
        "flower"u8.ToArray(),

        "good"u8.ToArray(),
        "new"u8.ToArray(),
        "great"u8.ToArray(),
        "big"u8.ToArray(),
        "small"u8.ToArray(),
        "high"u8.ToArray(),
        "long"u8.ToArray(),
        "short"u8.ToArray(),
        "young"u8.ToArray(),
        "beautiful"u8.ToArray(),
        "happy"u8.ToArray(),
        "sweet"u8.ToArray(),
        "fresh"u8.ToArray(),
        "juicy"u8.ToArray(),
        "delicious"u8.ToArray(),
        "tasty"u8.ToArray(),
        "bright"u8.ToArray(),
        "dark"u8.ToArray(),
        "fast"u8.ToArray(),
        "slow"u8.ToArray(),

        "run"u8.ToArray(),
        "walk"u8.ToArray(),
        "see"u8.ToArray(),
        "look"u8.ToArray(),
        "hear"u8.ToArray(),
        "speak"u8.ToArray(),
        "think"u8.ToArray(),
        "know"u8.ToArray(),
        "love"u8.ToArray(),
        "like"u8.ToArray(),
        "want"u8.ToArray(),
        "need"u8.ToArray(),
        "give"u8.ToArray(),
        "take"u8.ToArray(),
        "make"u8.ToArray(),
        "find"u8.ToArray(),
        "come"u8.ToArray(),
        "go"u8.ToArray(),
        "get"u8.ToArray(),
        "open"u8.ToArray(),
        "close"u8.ToArray(),

        "red"u8.ToArray(),
        "blue"u8.ToArray(),
        "green"u8.ToArray(),
        "yellow"u8.ToArray(),
        "black"u8.ToArray(),
        "white"u8.ToArray(),
        "river"u8.ToArray(),
        "mountain"u8.ToArray(),
        "book"u8.ToArray(),
        "music"u8.ToArray(),
        "game"u8.ToArray(),
        "food"u8.ToArray(),
        "car"u8.ToArray(),
        "road"u8.ToArray(),
        "light"u8.ToArray(),
        "computer"u8.ToArray(),
        "phone"u8.ToArray(),
        "strong"u8.ToArray(),
        "kind"u8.ToArray(),
        "quiet"u8.ToArray()
    ];

    public static ReadOnlySpan<byte> DotSpace => ".  "u8;
    public static ReadOnlySpan<byte> NewLine => "\n"u8;

    public static ReadOnlySpan<byte> GetRandomWord()
    {
        var index = Random.Shared.Next(Words.Length);
        return Words[index].AsSpan();
    }
}